[pytest]
addopts = -v -s --html=reports/report.html --self-contained-html
testpaths =
    tests
markers =
    ui: UI tests using Selenium WebDriver
    api: API tests using Requests
log_cli = true
log_cli_level = INFO
